[package]
name = "modcraft-launcher"
version = "0.7.0"
edition = "2021"

[dependencies]
bytesize = "1.3.0"
iced = { version = "0.10", features = ["system"] }

[profile.release]
lto = "thin"
strip = true
